services:
  nginx:
    container_name: nginx
    ports:
      - "8080:80"
    image: nginx
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /Users/banban/Desktop/lnmp/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - /Users/banban/Desktop/lnmp/nginx/conf/conf.d:/etc/nginx/conf.d
      - /Users/banban/Desktop/lnmp/nginx/html:/usr/share/nginx/html
      - /Users/banban/Desktop/lnmp/www/html/:/home/
    networks:
      - frontend
    links:
      - php7
  
  beanstalk:
    container_name: beanstalk5
    ports:
      - "11300:11300"
    image: schickling/beanstalkd:latest
    platform: linux/amd64
    environment:
      - TZ=Asia/Shanghai
    networks:
      - backend
  
  # php-fpm:
  #   container_name: php-fpm
  #   image: jiangqiao/php5.6-fpm-banban
  #   volumes:
  #     - /Users/banban/Desktop/lnmp/php/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
  #     - /Users/banban/Desktop/lnmp/php/conf.d:/usr/local/etc/php-fpm/php-fpm.d
  #     - /Users/banban/Desktop/lnmp/www/html/:/home/
  #     - /Users/banban/Desktop/lnmp/nginx/html:/var/www/html
  #     - /Users/banban/Desktop/lnmp/php/php.ini:/usr/local/etc/php/php.ini
  #   environment:
  #     - TZ=Asia/Shanghai # 设置时区
  #   networks:
  #     - frontend
  #     - backend
  #   links:
  #     - redis
  #     - mysql
  #   stdin_open: true
  #   tty: true

  php7:
    container_name: php7
    build: .
    image: php:7.2-fpm
    platform: linux/amd64
    volumes:
      - /Users/banban/Desktop/lnmp/php7/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
      - /Users/banban/Desktop/lnmp/php7/conf.d:/usr/local/etc/php-fpm.d
      - /Users/banban/Desktop/lnmp/www/html/:/home/
      - /Users/banban/Desktop/lnmp/nginx/html:/var/www/html
      - /Users/banban/Desktop/lnmp/php7/php.ini:/usr/local/etc/php/php.ini
    environment:
      - TZ=Asia/Shanghai # 设置时区
    networks:
      - frontend
      - backend
    links:
      - redis
      - mysql
    # stdin_open: true
    # tty: true      

  # php7:
  #   container_name: php7
  #   build: .
  #   image: jiangqiao/php-7.2.33-fpm-banban-2021-11:latest
  #   platform: linux/amd64
  #   volumes:
  #     - /Users/banban/Desktop/lnmp/php7/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
  #     - /Users/banban/Desktop/lnmp/php7/conf.d:/usr/local/etc/php-fpm.d
  #     - /Users/banban/Desktop/lnmp/www/html/:/home/
  #     - /Users/banban/Desktop/lnmp/nginx/html:/var/www/html
  #     - /Users/banban/Desktop/lnmp/php7/php.ini:/usr/local/etc/php/php.ini
  #   environment:
  #     - TZ=Asia/Shanghai # 设置时区
  #   networks:
  #     - frontend
  #     - backend
  #   links:
  #     - redis
  #     - mysql

  redis:
    container_name: redis
    image: redis:alpine3.8
    ports:
      - "6380:6379"
    volumes:
      - /Users/banban/Desktop/lnmp/redis/redis.conf:/usr/local/redis/redis.conf:ro
      - /Users/banban/Desktop/lnmp/redis/data:/data
    environment:
      - TZ=Asia/Shanghai # 设置时区
    command:
      redis-server /usr/local/redis/redis.conf --appendonly yes
    networks:
      - frontend
  
  mysql:
    container_name: mysql
    image: mysql:5.7
    platform: linux/amd64
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - /Users/banban/Desktop/lnmp/mysql/data:/var/lib/mysql
      - /Users/banban/Desktop/lnmp/mysql/conf.d:/etc/mysql/conf.d
    networks:
      - backend
  
  nsqlookupd:
    container_name: nsqlookupd5
    image: nsqio/nsq:latest
    command: /nsqlookupd
    networks:
      - backend
    ports:
      - "4160:4160"
      - "4161:4161"
  
  nsqd:
    container_name: nsqd5
    ports:
      - "4150:4150"
      - "4151:4151"
    image: nsqio/nsq:latest
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    networks:
      - backend
  
  nsqadmin:
    image: nsqio/nsq:latest
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    networks:
      - backend
    depends_on:
      - nsqlookupd
    ports:
      - "4171:4171"

networks:
  frontend:
  backend:

volumes:
  db-data: